server.port: 14562
management.port: 14563
endpoints.shutdown.enabled: true
dvision.out-directory: cams/cam-motion-grabber
motion-detection-service.baseurl: http://localhost:14562

---

spring.profiles: local

---

spring.profiles: autosmall

---

spring.profiles: autolarge

---

spring.profiles: man

---

spring.profiles: prod

dvision.out-directory: /mnt/catalina/public/cams/cam-motion-grabber
