server.port: 8080

# Defaults, overriden by environment variables with the same names
dvision.out-directory: cams/cam-motion-grabber
dvision.baseurl: http://localhost:14562
dvision.apiuser: dvisionuser
dvision.apipassword: dvisionpassword

---

spring.profiles: local

---

spring.profiles: autosmall

---

spring.profiles: autolarge

---

spring.profiles: man

---

spring.profiles: prod

dvision.out-directory: /cam-motion-grabber
