server.port: 8080

# Defaults, overriden by environment variables with the same names
dvision.apiuser: dvisionuser
dvision.apipassword: dvisionpassword

---
spring.profiles: local

---
spring.profiles: prod
