server.port: 14562
management.port: 14563
endpoints.shutdown.enabled: true
dvision.outdirectory: cams/cam-motion-grabber

---

spring.profiles: local

---

spring.profiles: autosmall

---

spring.profiles: autolarge

---

spring.profiles: man

---

spring.profiles: prod

dvision.outdirectory: /mnt/catalina/public/cams/cam-motion-grabber
